// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebApp.Data;

#nullable disable

namespace WebApp.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.10");

            modelBuilder.Entity("WebApp.Models.Person", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("MiddleName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Organization")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("FirstName", "LastName", "MiddleName", "Organization")
                        .IsUnique();

                    b.ToTable("Persons");
                });

            modelBuilder.Entity("WebApp.Models.TaskQuestion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Order")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Points")
                        .HasColumnType("INTEGER");

                    b.Property<string>("QuestionType")
                        .IsRequired()
                        .HasMaxLength(21)
                        .HasColumnType("TEXT");

                    b.Property<int>("TaskId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TextKk")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TextRu")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("TaskId");

                    b.ToTable("TaskQuestions");

                    b.HasDiscriminator<string>("QuestionType").HasValue("TaskQuestion");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("WebApp.Models.TestTask", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("DescriptionKk")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("DescriptionRu")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("MaxPoints")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Number")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TimeLimitSeconds")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TitleKk")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TitleRu")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("TestTasks");
                });

            modelBuilder.Entity("WebApp.Models.UserAnswer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("AnsweredAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsCorrect")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ParticipantId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Points")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SelectedAnswer")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("TaskId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("TaskId");

                    b.ToTable("UserAnswers");
                });

            modelBuilder.Entity("WebApp.Models.CategorizationQuestion", b =>
                {
                    b.HasBaseType("WebApp.Models.TaskQuestion");

                    b.Property<string>("Category1Kk")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Category1Ru")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Category2Kk")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Category2Ru")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CorrectMapping")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TermsKk")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TermsRu")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasDiscriminator().HasValue("Categorization");
                });

            modelBuilder.Entity("WebApp.Models.MatchingQuestion", b =>
                {
                    b.HasBaseType("WebApp.Models.TaskQuestion");

                    b.Property<string>("CorrectMatches")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("LeftItemsKk")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("LeftItemsRu")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("RightItemsKk")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("RightItemsRu")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasDiscriminator().HasValue("Matching");
                });

            modelBuilder.Entity("WebApp.Models.MultipleChoiceQuestion", b =>
                {
                    b.HasBaseType("WebApp.Models.TaskQuestion");

                    b.Property<int>("CorrectOptionIndex")
                        .HasColumnType("INTEGER");

                    b.Property<string>("OptionsKk")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("OptionsRu")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasDiscriminator().HasValue("MultipleChoice");
                });

            modelBuilder.Entity("WebApp.Models.TableQuestion", b =>
                {
                    b.HasBaseType("WebApp.Models.TaskQuestion");

                    b.Property<string>("CorrectAnswers")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CorrectOptimalP")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CorrectOptimalQ")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("EditableColumns")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("HeadersKk")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("HeadersRu")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TableDataKk")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TableDataRu")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasDiscriminator().HasValue("Table");
                });

            modelBuilder.Entity("WebApp.Models.TrueFalseQuestion", b =>
                {
                    b.HasBaseType("WebApp.Models.TaskQuestion");

                    b.Property<bool>("CorrectAnswer")
                        .HasColumnType("INTEGER");

                    b.HasDiscriminator().HasValue("TrueFalse");
                });

            modelBuilder.Entity("WebApp.Models.TaskQuestion", b =>
                {
                    b.HasOne("WebApp.Models.TestTask", "Task")
                        .WithMany("Questions")
                        .HasForeignKey("TaskId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Task");
                });

            modelBuilder.Entity("WebApp.Models.UserAnswer", b =>
                {
                    b.HasOne("WebApp.Models.TestTask", "Task")
                        .WithMany()
                        .HasForeignKey("TaskId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Task");
                });

            modelBuilder.Entity("WebApp.Models.TestTask", b =>
                {
                    b.Navigation("Questions");
                });
#pragma warning restore 612, 618
        }
    }
}
